name: Test Action with Email

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2003064@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
